apiVersion: apps/v1
kind: Deployment
metadata:
  name: caseprog
  labels:
    app: caseprog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caseprog
  template:
    metadata:
      labels:
        app: caseprog
    spec:
      containers:
      - name: caseprog
        image: localhost/caseprog:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000